# exemple : 
# server_ip[:port] : hostname [other_hostname] [, user_id] [other_user_id]
# [optional]
# 192.168.1.1:2244 : myserver
# 192.168.1.2 : myotherserver nginx web
# 192.168.1.3 : thirdserver, abcdefgh
# 192.168.1.4 : fourthserver, abcdefgh ijklmnop

